[tool.poetry]
name = "airflow-tutorials"
version = "0.1.0"
description = ""
authors = ["jaden <jaden.b.jeong@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
